---
- name: copy SSL certificates
  copy:
    content: "{{ item.content | default(omit) }}"
    dest: "{{ item.dest }}"
    owner: "{{ ssl_path_owner }}"
    group: "{{ ssl_path_group }}"
    mode: "700"
  register: ssl_copy_cert_data
  when:
    - item.content != ''
  with_items:
  - { content: "{{ ssl_privkey_data | default('') }}", dest: "{{ ssl_privkey_path }}" }
  - { content: "{{ ssl_cert_data | default('') }}", dest: "{{ ssl_cert_path }}" }
  - { content: "{{ ssl_intermediate_cert_data | default('') }}", dest: "{{ ssl_intermediate_cert_path }}" }
  no_log: true
  tags:
  - ssl

- name: check if pem exist
  stat:
    path: "{{ ssl_pem_path }}"
  register: ssl_stat_pem
  tags:
  - ssl

- name: assemble crt and intermediate crt into pem file
  assemble:
    dest: "{{ ssl_pem_path }}"
    src: "{{ ssl_path }}"
    regexp: "({{ ssl_cert_path | basename }}|{{ ssl_intermediate_cert_path | basename }})"
  when: (not ssl_stat_pem.stat.exists) or (ssl_copy_cert_data.changed)
  tags:
  - ssl

# https://weakdh.org/
- name: generate strong DHE parameter
  command: openssl dhparam -out {{ssl_dhparam_path}} {{ssl_dhparam_size}} creates={{ssl_dhparam_path}}
  when: ssl_generate_dh_param
  tags:
  - ssl
